# Aqui se indica la imagen
FROM nodered/node-red:latest

# Instalar nodos (forma correcta según)
RUN npm install \
    @flowfuse/node-red-dashboard \
    node-red-contrib-influxdb \
    node-red-contrib-slack \
    node-red-contrib-slack-files \
    node-red-node-serialport \
    node-red-contrib-web-worldmap \
    node-red-contrib-whatsapp-cmb \
    node-red-node-email \
    node-red-node-geofence