{
 "title": "Dashboard Grafana",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Roll A",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"rollA\") |> last()"
    }
   ]
  },
  {
   "title": "Pitch A",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"pitchA\") |> last()"
    }
   ]
  },
  {
   "title": "Yaw A",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"yawA\") |> last()"
    }
   ]
  },
  {
   "title": "Roll F",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"rollF\") |> last()"
    }
   ]
  },
  {
   "title": "Pitch F",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"pitchF\") |> last()"
    }
   ]
  },
  {
   "title": "Yaw F",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"yawF\") |> last()"
    }
   ]
  },
  {
   "title": "ECG",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"project\") |> range(start: v.timeRangeStart, stop: v.timeRangeStop) |> filter(fn: (r) => r._measurement == \"prototype_data\" and r._field == \"ecg\") |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}